F04
YohannMaiVan/React-crazee-burger pull request #4
Opened 2023-09-22 15:11 UTC by YohannMaiVan

2023-09-23 14:08 UTC, vileaddev requested changes
Tout est bon, sauf les rectif à faire niveau rendu navigateur au niveau de : 
- marge de body
- dimensions du logo coté OrderPage

A part ça, tout est parfait 👌

2023-09-25 18:04 UTC, didierLaPasserelle approved these changes

2023-09-25 18:04 UTC, didierLaPasserelle commented on src/components/pages/order/OrderPage.jsx
> +      <div className="container">
OPTIONNEL : remplacer la div' par un composant qui lui va contenir Navbar & Main.

2023-09-25 18:04 UTC, didierLaPasserelle commented on src/components/reusable-ui/Logo.jsx
>        <img src="/images/logo-orange.png" alt="logo-crazee-burger" />
OPTIONNEL : Implémenter un props pour la src.

2023-09-25 19:38 UTC, vileaddev approved these changes
Pour moi, comme les commentaires de Didier sont optionnels, je valide ta PR. Tu peux merger ta PR :) Maintenant, si tu veux incorporer ses changements à lui, tu peux le faire et re git push par derrière et valider directement sans me demander mon avis :)

2023-09-26 09:49 UTC, merged